version: "3.8"
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"

  product-service:
    build: ./product-service
    ports:
      - "8001:8001"

  order-service:
    build: ./order-service
    ports:
      - "8002:8002"

  stock-service:
    build: ./stock-service
    ports:
      - "8003:8003"
